# Generated by Django 4.0.3 on 2022-04-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_patientinfo_phenotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='age',
            field=models.IntegerField(),
        ),
    ]
